// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmGrXmmpQUZqwqC2KCj2WRu8DLAUlYdtI',
    appId: '1:1064941811904:web:9f8db797016d12ba535525',
    messagingSenderId: '1064941811904',
    projectId: 'gemini-app-1b4b9',
    authDomain: 'gemini-app-1b4b9.firebaseapp.com',
    storageBucket: 'gemini-app-1b4b9.appspot.com',
    measurementId: 'G-8XDZ79X97C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFInT_JpszU4q9ldgcswPkuInqHDF-lQ',
    appId: '1:1064941811904:android:aa04c99335f313dc535525',
    messagingSenderId: '1064941811904',
    projectId: 'gemini-app-1b4b9',
    storageBucket: 'gemini-app-1b4b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX2DR1xqgB7WxHNfW3p4d9nScHfF80HcY',
    appId: '1:1064941811904:ios:8a4c079aa9c6f9c9535525',
    messagingSenderId: '1064941811904',
    projectId: 'gemini-app-1b4b9',
    storageBucket: 'gemini-app-1b4b9.appspot.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX2DR1xqgB7WxHNfW3p4d9nScHfF80HcY',
    appId: '1:1064941811904:ios:8a4c079aa9c6f9c9535525',
    messagingSenderId: '1064941811904',
    projectId: 'gemini-app-1b4b9',
    storageBucket: 'gemini-app-1b4b9.appspot.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmGrXmmpQUZqwqC2KCj2WRu8DLAUlYdtI',
    appId: '1:1064941811904:web:640e7818ba8a817c535525',
    messagingSenderId: '1064941811904',
    projectId: 'gemini-app-1b4b9',
    authDomain: 'gemini-app-1b4b9.firebaseapp.com',
    storageBucket: 'gemini-app-1b4b9.appspot.com',
    measurementId: 'G-8BRFC9VJY2',
  );
}
